# Generated by Django 3.0.4 on 2020-04-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=40)),
                ('productprice', models.IntegerField(default=0)),
                ('productquantity', models.IntegerField(default=1)),
                ('productimage', models.FileField(upload_to='myapp/img/')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.IntegerField(default=123),
        ),
    ]
