# Generated by Django 3.0.4 on 2020-04-23 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='reviewdate',
        ),
    ]
