# Generated by Django 3.0.4 on 2020-05-04 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='email',
            new_name='message_email',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='name',
            new_name='message_name',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='subject',
            new_name='message_subject',
        ),
    ]
