# Generated by Django 3.0.4 on 2020-05-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200504_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='productimage',
            field=models.FileField(default='testimonials.jpg', upload_to='myapp/img/'),
        ),
    ]
