# Generated by Django 3.0.4 on 2020-05-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_total',
            field=models.IntegerField(default=0),
        ),
    ]
