# Generated by Django 3.0.4 on 2020-05-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_cart_cart_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponcode', models.CharField(max_length=20)),
                ('coupondesc', models.CharField(max_length=50)),
            ],
        ),
    ]
