# Generated by Django 3.0.4 on 2020-05-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_coupon_couponamt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='couponamt',
            field=models.FloatField(default=1.0),
        ),
    ]
