# Generated by Django 3.0.4 on 2020-05-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20200506_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='billamt',
            field=models.FloatField(default=0.0),
        ),
    ]
