# Generated by Django 3.0.4 on 2020-05-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_coupon_billamt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='billamt',
        ),
        migrations.AddField(
            model_name='customer',
            name='billamt',
            field=models.FloatField(default=0.0),
        ),
    ]
