# Generated by Django 3.0.4 on 2020-05-06 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='cart_id',
        ),
    ]
