# Generated by Django 3.0.4 on 2020-05-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_billing_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='c_id',
        ),
    ]
