# Generated by Django 3.0.4 on 2020-05-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='b_id',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='c_id',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='p_id',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
