# Generated by Django 3.0.4 on 2020-05-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_auto_20200509_1650'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Billing',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
